### ISSUE TITLE
please tag and version this project

### ISSUE THREAD

**Issue by aviau** [cloudfoundry/gosigar#26]
Hello,

Can you please tag and version this project?

I am the Debian Maintainer for gosigar and versioning would help Debian keep up with development.

**Comment by onlyjob** [comment]
Tags/releases are useful for downstream package maintainers (in [Debian](http://debian.org) and other distributions) to export source tarballs, automatically track new releases and to declare dependencies between packages. Read more in the [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions).

Versioning provides additional benefits to encourage vendoring of a particular (e.g. latest stable) release contrary to random unreleased snapshots.

Also compatibility with [gopkg.in](http://labix.org/gopkg.in) could be useful.

Thank you.

See also

 * http://semver.org/
 * https://en.wikipedia.org/wiki/Software_versioning

**Comment by aviau** [comment]
Any news on this?

**Comment by cppforlife** [comment]
@aviau we can tag it as v1 at the current master. sound good?

**Comment by AaronO** [comment]
@cppforlife Following [semver](http://semver.org/) would be great

**Comment by doertedev** [comment]
hmm.... please?

**Comment by tamird** [comment]
@luan (picking you because you have recent commits): even if you don't do this, please remove the current "release" which is some ancient tag from 2013. Tools like golang/dep might prefer it to the master branch, which is probably very bad.

**Comment by dpb587-pivotal** [comment]
Created tag `v1.1.0` with latest master for improved tooling compatibility.

```
[[projects]]
  name = "github.com/cloudfoundry/gosigar"
  packages = [".","sys/windows"]
  revision = "dcb1afc219e4c99f21c37fb1ec22ed9ffe443317"
  version = "v1.1.0"
```
