### ISSUE TITLE
 Crashes on Windows XP on init

### ISSUE THREAD

**Issue by xiegeo** [cloudfoundry/gosigar#33]
panic: Failed to find GetTickCount64 procedure in kernel32: The specified procedure could not be found.

GetTickCount64 is Vista and up.

**Comment by charlievieth** [comment]
@xiegeo Thanks for creating an issue.  We originally added the Windows code with Server 2012 in mind, but causing older versions to panic isn't great.

This should be fixed with https://github.com/cloudfoundry/gosigar/pull/34.

**Comment by xiegeo** [comment]
Thank you, that looks like the simplest solution.
