### ISSUE TITLE
Darwin： no get 'syscall.NOTE_EXEC' event, and how get pid and ppid in one event？

### ISSUE THREAD

**Issue by cyongxue** [cloudfoundry/gosigar#42]
for _, ev := range events[:n] {
			pid := int(ev.Ident)

			switch ev.Fflags {
			case syscall.NOTE_FORK:
				fmt.Println("NOTE_FORK:", ev)
				w.Fork <- &ProcEventFork{ParentPid: pid}
			case syscall.NOTE_EXEC:
				fmt.Println("NOTE_EXEC:", ev)
				w.Exec <- &ProcEventExec{Pid: pid}
			case syscall.NOTE_EXIT:
				fmt.Println("NOTE_EXIT:", ev)
				w.RemoveWatch(pid)
				w.Exit <- &ProcEventExit{Pid: pid}
			}
		}

**Darwin：** no get 'syscall.NOTE_EXEC' event, and how get pid and ppid in one event？

**Comment by JimWen** [comment]
> for _, ev := range events[:n] { pid := int(ev.Ident)
> 
> ```
> 		switch ev.Fflags {
> 		case syscall.NOTE_FORK:
> 			fmt.Println("NOTE_FORK:", ev)
> 			w.Fork <- &ProcEventFork{ParentPid: pid}
> 		case syscall.NOTE_EXEC:
> 			fmt.Println("NOTE_EXEC:", ev)
> 			w.Exec <- &ProcEventExec{Pid: pid}
> 		case syscall.NOTE_EXIT:
> 			fmt.Println("NOTE_EXIT:", ev)
> 			w.RemoveWatch(pid)
> 			w.Exit <- &ProcEventExit{Pid: pid}
> 		}
> 	}
> ```
> 
> **Darwin：** no get 'syscall.NOTE_EXEC' event, and how get pid and ppid in one event？

hi did you fix this problem
