### ISSUE TITLE
Memory calculation inside containerized environments

### ISSUE THREAD

**Issue by mudler** [cloudfoundry/gosigar#48]
Hi :wave: 

https://github.com/cloudfoundry/gosigar/blob/a3af48c7e16a418be8366ffed86df345c5c4703d/sigar_linux.go#L319

Is used in log-cache https://github.com/cloudfoundry/log-cache/blob/526a0fd20d0308de00e5a3018047219428e31653/internal/cache/memory_analyzer.go#L41 - which if being run inside a container (e.g. inside kubernetes) would report the node memory available, not the one assigned to the container under cgroups (which in such case would be in `/sys/fs/cgroup/memory/memory.limit_in_bytes`).

In such situation, log-cache would start allocating memory depending on such values, causing a varying range of issues (OOMKills, performance degradation, etc.).

This seems to be an underlying issue with the containerization engine used, as they could behave differently ( https://github.com/opencontainers/runc/issues/400 ). My suggestion would be to detect if we are in a cgroup and - only in such case - report the memory assigned ( or for sake of simplicity, even only an option to turn on this feature ): would you consider such a PR/proposal?

To note: this is a different issue from #32, which suggests to read differently from `/proc/meminfo`.

See also https://github.com/moby/moby/issues/20688 for more context and this article from heroku: https://fabiokung.com/2014/03/13/memory-inside-linux-containers/

**Comment by andreas-kupries** [comment]
Proposed fix: #50
