### ISSUE TITLE
Security vulnerabilities in dependencies of latest release

### ISSUE THREAD

**Issue by dveeden** [cloudfoundry/gosigar#65]
Looking at https://deps.dev/go/github.com%2Fcloudfoundry%2Fgosigar this shows a few issues with dependencies that seems to be fixed after v1.3.4 was released. It might be good to release a new version with these improvements.

**Comment by rkoster** [comment]
Thanks for the pointing this out, will create a story on our backlog to work on this.

**Comment by rkoster** [comment]
Story created: https://www.pivotaltracker.com/story/show/184270420 (private project, but here as a cross reference for people who can access the tracker project).

**Comment by selzoc** [comment]
We now have a v1.3.5 and v1.3.6!  Our pipeline should automatically tag new versions as dependency bumps come in.
